import GroupProvider from '@/providers/GroupProvider';
import axios from 'axios';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'List Group',
	description: 'Generated by create next app',
};

axios.defaults.baseURL = 'http://localhost:3000';

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<GroupProvider>{children}</GroupProvider>
			</body>
		</html>
	);
}
